"""Data seed terkurasi: pasal-pasal kunci ketenagakerjaan & BPJS Ketenagakerjaan.

Dipakai saat database kosong agar API langsung berisi data. Konten berupa
rangkuman/parafrase, bukan teks resmi — pengguna tetap diarahkan ke sumber
resmi (source_url / pdf_url) untuk teks lengkapnya.
"""

SEED_REGULATIONS = [
    {
        "slug": "uu-13-2003",
        "number": "UU No. 13 Tahun 2003",
        "title": "Undang-Undang tentang Ketenagakerjaan",
        "type": "UU",
        "year": 2003,
        "about": "Ketenagakerjaan",
        "status": "diubah (sebagian oleh UU 11/2020 & UU 6/2023)",
        "programs": ["PHK", "PESANGON"],
        "source": "seed",
        "source_url": "https://peraturan.bpk.go.id",
        "articles": [
            {"pasal": "1", "title": "Ketentuan Umum", "programs": [], "content": "Definisi istilah ketenagakerjaan: pekerja/buruh, pemberi kerja, perjanjian kerja, pemutusan hubungan kerja (PHK), hubungan kerja, dan lain-lain."},
            {"pasal": "150", "title": "Kewajiban Pemberi Kerja", "programs": ["PHK"], "content": "Pemberi kerja wajib mengusahakan agar tidak terjadi PHK; apabila tidak dapat dihindari, maksud dan alasan PHK diberitahukan kepada pekerja dan/atau serikat pekerja."},
            {"pasal": "151", "title": "Upaya Penyelesaian PHK", "programs": ["PHK"], "content": "PHK harus diupayakan diselesaikan secara musyawarah; bila tidak tercapai, diselesaikan melalui prosedur penyelesaian perselisihan hubungan industrial."},
            {"pasal": "156", "title": "Kewajiban Pembayaran Pesangon, UPMK, dan UPH (asli, sebelum Cipta Kerja)", "programs": ["PHK", "PESANGON"], "content": "Pengusaha wajib membayar uang pesangon dan/atau uang penghargaan masa kerja (UPMK) dan uang penggantian hak (UPH). Besaran tergantung masa kerja. Ketentuan ini telah diubah — lihat UU 6/2023 dan PP 35/2021."},
            {"pasal": "157", "title": "Penetapan Komponen Upah sebagai Dasar Perhitungan Pesangon", "programs": ["PESANGON"], "content": "Komponen upah yang digunakan sebagai dasar perhitungan pesangon terdiri atas upah pokok dan tunjangan tetap yang diberikan kepada pekerja dan keluarganya."},
            {"pasal": "161", "title": "PHK karena Pelanggaran", "programs": ["PHK"], "content": "Pekerja yang melakukan pelanggaran yang telah diatur dalam perjanjian kerja/peraturan perusahaan dapat diputus hubungan kerjanya setelah diberikan surat peringatan berturut-turut (SP1, SP2, SP3), masing-masing berlaku 6 bulan, kecuali ditentukan lain."},
            {"pasal": "164", "title": "PHK karena Perubahan Status/Penggabungan", "programs": ["PHK"], "content": "Pekerja dapat mengajukan PHK apabila perusahaan mengalami perubahan status, penggabungan, peleburan, atau perubahan kepemilikan dan pekerja tidak bersedia melanjutkan hubungan kerja."},
            {"pasal": "165", "title": "PHK karena Perusahaan Bangkrut", "programs": ["PHK"], "content": "Pengusaha dapat melakukan PHK bila perusahaan dinyatakan pailit/dibangkrutkan. Besaran pesangon diatur lebih lanjut dalam peraturan pelaksana (PP 35/2021)."},
            {"pasal": "168", "title": "Pekerja Mangkir", "programs": ["PHK"], "content": "Pekerja yang mangkir 5 hari kerja atau lebih berturut-turut tanpa keterangan tertulis yang disertai bukti sah dan telah dipanggil 2 kali secara patut dapat di-PHK karena mangkir."},
            {"pasal": "169", "title": "Permintaan PHK oleh Pekerja karena Tindakan Pengusaha", "programs": ["PHK", "PESANGON"], "content": "Pekerja dapat meminta PHK karena pengusaha melakukan perbuatan tertentu (menganiaya, tidak membayar upah tepat waktu 3 bulan berturut-turut, tidak melaksanakan kewajiban, dll)."},
        ],
    },
    {
        "slug": "uu-6-2023",
        "number": "UU No. 6 Tahun 2023",
        "title": "Penetapan Perppu 2/2022 tentang Cipta Kerja menjadi Undang-Undang",
        "type": "UU",
        "year": 2023,
        "about": "Cipta Kerja (termasuk klaster ketenagakerjaan)",
        "status": "berlaku",
        "programs": ["PHK", "PESANGON"],
        "source": "seed",
        "source_url": "https://peraturan.bpk.go.id",
        "articles": [
            {"pasal": "59", "title": "PKWT (Perjanjian Kerja Waktu Tertentu) — ketentuan dalam Bab IV Paragraf 2 UU 13/2003 sebagaimana diubah", "programs": [], "content": "Mengatur PKWT termasuk jangka waktu dan kompensasi; rincian teknis dalam PP 35/2021."},
            {"pasal": "81", "title": "Perubahan atas UU 13/2003 (klaster ketenagakerjaan)", "programs": ["PHK", "PESANGON"], "content": "Mengubah/menghapus berbagai ketentuan UU 13/2003 — antara lain PHK (Pasal 151, 156), pesangon, alih daya, waktu kerja, cuti. Detail perhitungan dirujuk ke PP 35/2021."},
        ],
    },
    {
        "slug": "pp-35-2021",
        "number": "PP No. 35 Tahun 2021",
        "title": "PKWT, Alih Daya, Waktu Kerja dan Istirahat, dan Pemutusan Hubungan Kerja",
        "type": "PP",
        "year": 2021,
        "about": "Perjanjian Kerja Waktu Tertentu, Alih Daya, Waktu Kerja dan Waktu Istirahat, dan Pemutusan Hubungan Kerja",
        "status": "berlaku",
        "programs": ["PHK", "PESANGON"],
        "source": "seed",
        "source_url": "https://peraturan.bpk.go.id",
        "articles": [
            {"pasal": "36", "title": "Alasan PHK", "programs": ["PHK"], "content": "PHK dapat terjadi karena: penggabungan/peleburan/pemisahan perusahaan, pengambilalihan, efisiensi, perusahaan rugi/tutup/pailit/PKPU, keadaan memaksa (force majeur), kesalahan berat, pelanggaran PK/PP/PKB, putusan pengadilan, pengunduran diri, mangkir, pensiun, sakit berkepanjangan/cacat/meninggal dunia."},
            {"pasal": "37", "title": "Larangan PHK", "programs": ["PHK"], "content": "PHK dilarang antara lain karena: sakit menurut keterangan dokter (≤ 12 bulan), menjalankan kewajiban negara/ibadah, menikah, hamil/melahirkan/keguguran/menyusui, hubungan darah/perkawinan sesama pekerja, mendirikan/menjadi pengurus serikat pekerja, mengadukan pengusaha, perbedaan paham/agama/suku/jenis kelamin, cacat tetap/sakit akibat kecelakaan kerja."},
            {"pasal": "40", "title": "UU Pesangon (UP) — Tabel Besaran", "programs": ["PESANGON"], "content": "Besaran UP: masa kerja <1 thn = 1 bulan upah; 1–<2 = 2 bln; 2–<3 = 3 bln; 3–<4 = 4 bln; 4–<5 = 5 bln; 5–<6 = 6 bln; 6–<7 = 7 bln; 7–<8 = 8 bln; ≥8 thn = 9 bulan upah."},
            {"pasal": "41", "title": "UPMK — Tabel Besaran", "programs": ["PESANGON"], "content": "Besaran UPMK: masa kerja 3–<6 thn = 2 bulan upah; 6–<9 = 3 bln; 9–<12 = 4 bln; 12–<15 = 5 bln; 15–<18 = 6 bln; 18–<21 = 7 bln; 21–<24 = 8 bln; ≥24 thn = 10 bulan upah."},
            {"pasal": "42", "title": "Uang Penggantian Hak (UPH)", "programs": ["PESANGON"], "content": "UPH meliputi: cuti tahunan yang belum diambil dan belum gugur; biaya/ongkos pulang ke tempat pekerja diterima bekerja (jika ada); dan hal-hal lain yang ditetapkan dalam perjanjian kerja/peraturan perusahaan/PKB."},
            {"pasal": "43", "title": "Pengurangan Pesangon dalam Kondisi Tertentu", "programs": ["PESANGON"], "content": "Perusahaan yang mengalami kesulitan (rugi, efisiensi, PKPU, dll) dapat membayar pesangon sesuai angka pengali tertentu (mis. 0,5x atau 1x UP) tergantung alasan PHK sesuai rincian Pasal 43."},
            {"pasal": "45", "title": "PHK karena Perubahan Status/Penggabungan", "programs": ["PHK", "PESANGON"], "content": "Hak pekerja atas PHK karena perubahan status, penggabungan, peleburan, atau pengambilalihan perusahaan sesuai klasifikasi pasal ini."},
            {"pasal": "47", "title": "PHK karena Kesalahan Berat / Pelanggaran", "programs": ["PHK", "PESANGON"], "content": "Pekerja yang di-PHK karena kesalahan berat berhak atas UPH dan uang pisah; karena pelanggaran (setelah SP bertahap) berhak pesangon 0,5x UP, UPMK 1x, dan UPH."},
            {"pasal": "52", "title": "Uang Pisah", "programs": ["PESANGON"], "content": "Uang pisah diberikan pada PHK karena pengunduran diri atas kemauan sendiri dan kesalahan berat, besarnya diatur dalam perjanjian kerja/peraturan perusahaan/PKB."},
            {"pasal": "56", "title": "Alternatif Pembayaran saat Perusahaan Rugi", "programs": ["PESANGON"], "content": "Dalam kondisi perusahaan merugi atau restrukturisasi, pembayaran hak pekerja dapat disepakati lain sesuai mekanisme yang diatur pasal ini."},
        ],
    },
    {
        "slug": "pp-46-2015",
        "number": "PP No. 46 Tahun 2015",
        "title": "Penyelenggaraan Program Jaminan Hari Tua (JHT)",
        "type": "PP",
        "year": 2015,
        "about": "Penyelenggaraan Program Jaminan Hari Tua",
        "status": "berlaku (diubah sebagian, a.l. PP 26/2023)",
        "programs": ["JHT"],
        "source": "seed",
        "source_url": "https://peraturan.bpk.go.id",
        "articles": [
            {"pasal": "14", "title": "Iuran JHT", "programs": ["JHT"], "content": "Iuran JHT 5,7% dari upah sebulan: 3,7% ditanggung pemberi kerja dan 2% ditanggung pekerja."},
            {"pasal": "19", "title": "Manfaat JHT", "programs": ["JHT"], "content": "Manfaat JHT berupa uang tunai sebesar akumulasi iuran ditambah hasil pengembangannya."},
            {"pasal": "20", "title": "Pembayaran Manfaat JHT", "programs": ["JHT"], "content": "Manfaat JHT dibayarkan saat peserta mencapai usia pensiun, meninggal dunia, atau cacat total tetap; pengambilan sebagian/penuh sebelum pensiun diatur lebih lanjut (Permenaker 19/2015 s.d. perubahannya)."},
        ],
    },
    {
        "slug": "pp-45-2015",
        "number": "PP No. 45 Tahun 2015",
        "title": "Penyelenggaraan Program Jaminan Pensiun (JP)",
        "type": "PP",
        "year": 2015,
        "about": "Penyelenggaraan Program Jaminan Pensiun",
        "status": "berlaku",
        "programs": ["JP"],
        "source": "seed",
        "source_url": "https://peraturan.bpk.go.id",
        "articles": [
            {"pasal": "4", "title": "Kepesertaan JP", "programs": ["JP"], "content": "Kepesertaan JP bersifat wajib bagi pekerja penerima upah (perusahaan) dan bukan penerima upah (pekerja mandiri) yang memenuhi syarat, kecuali yang telah mencapai usia pensiun."},
            {"pasal": "23", "title": "Iuran JP", "programs": ["JP"], "content": "Iuran JP untuk pekerja penerima upah 3% dari upah: 2% ditanggung pemberi kerja dan 1% ditanggung pekerja. Upah sebagai dasar perhitungan memiliki batas maksimal yang disesuaikan tahunan."},
            {"pasal": "28", "title": "Manfaat Pensiun Hari Tua", "programs": ["JP"], "content": "Manfaat pensiun hari tua berupa sejumlah uang yang dibayarkan setiap bulan dan memenuhi masa iur minimum 15 tahun saat peserta memasuki usia pensiun sampai meninggal dunia."},
        ],
    },
    {
        "slug": "pp-37-2021",
        "number": "PP No. 37 Tahun 2021",
        "title": "Penyelenggaraan Program Jaminan Kehilangan Pekerjaan (JKP)",
        "type": "PP",
        "year": 2021,
        "about": "Penyelenggaraan Program Jaminan Kehilangan Pekerjaan",
        "status": "berlaku",
        "programs": ["JKP"],
        "source": "seed",
        "source_url": "https://peraturan.bpk.go.id",
        "articles": [
            {"pasal": "3", "title": "Iuran JKP", "programs": ["JKP"], "content": "Iuran program JKP sebesar 0,46% dari upah sebulan yang dibayarkan pemberi kerja (berasal dari subsidi pemerintah 0,22%, subsidi program JKK 0,14%, dan program JKM 0,10%)."},
            {"pasal": "18", "title": "Manfaat JKP", "programs": ["JKP"], "content": "Manfaat JKP meliputi: uang tunai, akses informasi pasar kerja, dan pelatihan kerja bagi peserta yang mengalami PHK, dengan masa kerja/iur tertentu."},
            {"pasal": "22", "title": "Besaran Uang Tunai JKP", "programs": ["JKP"], "content": "Uang tunai JKP dibayarkan paling banyak 6 bulan upah: 3 bulan pertama sebesar 45% dari upah dan 3 bulan berikutnya sebesar 25% dari upah, dengan batas atas upah yang ditetapkan."},
        ],
    },
    {
        "slug": "uu-24-2011",
        "number": "UU No. 24 Tahun 2011",
        "title": "Badan Penyelenggara Jaminan Sosial (BPJS)",
        "type": "UU",
        "year": 2011,
        "about": "Badan Penyelenggara Jaminan Sosial",
        "status": "berlaku",
        "programs": ["JHT", "JP", "JKK", "JKM", "JKP"],
        "source": "seed",
        "source_url": "https://peraturan.bpk.go.id",
        "articles": [
            {"pasal": "6", "title": "Tugas BPJS Ketenagakerjaan", "programs": ["JHT", "JP", "JKK", "JKM", "JKP"], "content": "BPJS Ketenagakerjaan bertugas menyelenggarakan program jaminan kecelakaan kerja, jaminan hari tua, jaminan pensiun, jaminan kematian, dan jaminan kehilangan pekerjaan."},
            {"pasal": "14", "title": "Kewajiban Pemberi Kerja Mendaftarkan", "programs": ["JHT", "JP", "JKK", "JKM", "JKP"], "content": "Setiap pemberi kerja wajib mendaftarkan dirinya dan pekerjanya sebagai peserta kepada BPJS Ketenagakerjaan sesuai program jaminan sosial yang diikuti."},
            {"pasal": "15", "title": "Kewajiban Melapor Data", "programs": [], "content": "Pemberi kerja wajib memberikan data kepesertaan yang benar dan melaporkan perubahan upah pekerja serta status pekerjaan kepada BPJS Ketenagakerjaan."},
            {"pasal": "17", "title": "Sanksi Administratif", "programs": [], "content": "Pemberi kerja yang tidak memenuhi kewajiban dikenai sanksi administratif berupa teguran tertulis, denda, dan/atau tidak mendapatkan pelayanan publik tertentu."},
        ],
    },
]
